In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

Q1. The dataframe df has 17 columns. The column total_revenue contains total revenues and column revenue_json contains the breakdown of the total_revenue in multiple component. Write a code to calculcate the percentage contribution of dfp component in total revenue. This should run in less than 1 minute

In [15]:
total_revenue = ['98.46', '42.24', '34.21', '66.32', '72.72']
# revenue_json = {'dfp': [3.49,3.29,2.19,2.69,2.89], 'ga': [3.19,2.29,1.19,2.39,2.19], 'avantis': [1.19,2.59,1.18,2.22,2.17]}
revenue_json = ["{'dfp':3.49, 'ga':3.19, 'avantis':1.19}", "{'dfp':3.29, 'ga':2.29, 'avantis':2.59}", "{'dfp':2.49, 'ga':3.19, 'avantis':2.19}", "{'dfp':2.29, 'ga':4.19, 'avantis':3.19}", "{'dfp':2.59, 'ga':2.14, 'avantis':5.19}"]

In [16]:
df = pd.DataFrame({'total_revenue':total_revenue, 'revenue_json':revenue_json})
df

  total_revenue                             revenue_json
0         98.46  {'dfp':3.49, 'ga':3.19, 'avantis':1.19}
1         42.24  {'dfp':3.29, 'ga':2.29, 'avantis':2.59}
2         34.21  {'dfp':2.49, 'ga':3.19, 'avantis':2.19}
3         66.32  {'dfp':2.29, 'ga':4.19, 'avantis':3.19}
4         72.72  {'dfp':2.59, 'ga':2.14, 'avantis':5.19}

In [17]:
df['revenue_json'] = df['revenue_json'].apply(lambda x: eval(x))
df

  total_revenue                                revenue_json
0         98.46  {'dfp': 3.49, 'ga': 3.19, 'avantis': 1.19}
1         42.24  {'dfp': 3.29, 'ga': 2.29, 'avantis': 2.59}
2         34.21  {'dfp': 2.49, 'ga': 3.19, 'avantis': 2.19}
3         66.32  {'dfp': 2.29, 'ga': 4.19, 'avantis': 3.19}
4         72.72  {'dfp': 2.59, 'ga': 2.14, 'avantis': 5.19}

In [19]:
df['dfp_contribution'] = df['revenue_json'].apply(lambda x: x.get('dfp'))
df

  total_revenue                                revenue_json  dfp_contribution
0         98.46  {'dfp': 3.49, 'ga': 3.19, 'avantis': 1.19}              3.49
1         42.24  {'dfp': 3.29, 'ga': 2.29, 'avantis': 2.59}              3.29
2         34.21  {'dfp': 2.49, 'ga': 3.19, 'avantis': 2.19}              2.49
3         66.32  {'dfp': 2.29, 'ga': 4.19, 'avantis': 3.19}              2.29
4         72.72  {'dfp': 2.59, 'ga': 2.14, 'avantis': 5.19}              2.59

In [28]:
# print(df.dtypes)

total_revenue        object
revenue_json         object
dfp_contribution    float64
dtype: object

In [31]:
df['dfp_contribution_percent'] = 100.0*df['dfp_contribution']/df['total_revenue'].astype(float)
df

,total_revenue,revenue_json,dfp_contribution,dfp_contribution_percent
0,98.46,"{'dfp': 3.49, 'ga': 3.19, 'avantis': 1.19}",3.49,3.544587
1,42.24,"{'dfp': 3.29, 'ga': 2.29, 'avantis': 2.59}",3.29,7.788826
2,34.21,"{'dfp': 2.49, 'ga': 3.19, 'avantis': 2.19}",2.49,7.278574
3,66.32,"{'dfp': 2.29, 'ga': 4.19, 'avantis': 3.19}",2.29,3.452955
4,72.72,"{'dfp': 2.59, 'ga': 2.14, 'avantis': 5.19}",2.59,3.561606

In [35]:
answer = df['dfp_contribution'].sum()/df['dfp_contribution'].count()
answer

# answer = df['dfp_contribution_percent'].mean()
# answer

2.8299999999999996

Q2. Estiamte the total DFP revenue on 14th July 2023 for 1000$ spends on 1,000,000 clicks.

To estimate the total DFP revenue on 14th July 2023 for $1000 spent on 1,000,000 clicks, we need some additional information. Specifically, we need the average revenue generated per click (revenue per click) from the DFP component on that date. (Data Insufficient)